### ISSUE TITLE
Where is the P2-Quiz source code?

### ISSUE THREAD

**Issue by WiBla** [OpenClassrooms-Student-Center/Vue#2]
We need additional info in order to fill in the part 2 quiz, but when clicking the given link, we are pointed at the root of the repository.
I checked around to see if I could find the source code that was needed, but only found the part-2 folder that seems incomplete?

>**Question 2**
>**The homepage is unable to render the `title` data property. Why is this happening?**

[part-2](https://github.com/OpenClassrooms-Student-Center/Vue/tree/master/part-2) folder only includes a freshly created project, I was not able to find any "title" data anywhere 🤔
I thankfully managed to fill in the quiz by replying to what made the most sense, but that needs to change for future students.

**Comment by radifar** [comment]
The link is pointing to master branch, while the assignment is in another branch. To go to Chapter 2 - Part 2 there are two ways you can do. First is by selecting the 'branch dropdown' below the Code tab. The second way is to open the link (Chapter 2, Part 2, Begin Branch) in README.md.

Hope that helps.

**Comment by bencodezen** [comment]
@WiBla Thanks you so much for reporting this. My sincerest apologies for the confusion 🙇.

Turns out some of the code that I had initially created did not get attached to the repo for some reason, so I've gone ahead and pushed an update to `master` to reduce confusion (and updated the link on the quiz itself).

https://github.com/OpenClassrooms-Student-Center/Vue/tree/master/part-2-quiz

If you have any other questions or feedback for the course, please don't hesitate to open additional issues and I'll be sure to respond!
